In [2]:
import numpy as np
import torch
import tensorflow

# Permutations Tensors

In [3]:
X = np.random.rand(2,3)

In [4]:
print(X.shape)
X

(2, 3)


array([[0.99985136, 0.95523494, 0.02473813],
       [0.45367883, 0.11190415, 0.90120607]])

In [5]:
X2 = np.einsum('ij->ji', X)
print(X2.shape)
X2

(3, 2)


array([[0.99985136, 0.45367883],
       [0.95523494, 0.11190415],
       [0.02473813, 0.90120607]])

In [6]:
X3 = torch.einsum('ij->ji', torch.tensor(X))
print(X3.shape)
X3

torch.Size([3, 2])


tensor([[0.9999, 0.4537],
        [0.9552, 0.1119],
        [0.0247, 0.9012]], dtype=torch.float64)

# Summation

In [7]:
X_torch = torch.tensor(X)
X_tf = tensorflow.convert_to_tensor(X)
sum1 = np.einsum('ij->', X)
sum2 = torch.einsum('ij->', X_torch)
sum3 = tensorflow.einsum('ij->', X_tf)
print("sum1 = ", sum1)
print("sum2 = ", sum2)
print("sum3 = ", sum3)

sum1 =  3.4466134807906936
sum2 =  tensor(3.4466, dtype=torch.float64)
sum3 =  tf.Tensor(3.4466134807906936, shape=(), dtype=float64)


In [8]:
X.sum() == sum1

True

# Columns Summation

In [9]:
col_sum1 = np.einsum('ij->j', X)
col_sum2 = tensorflow.einsum('ij->j', X_tf)
col_sum3 = torch.einsum('ij->j', X_torch)
col_sum1, col_sum2, col_sum3

(array([1.45353019, 1.06713909, 0.9259442 ]),
 <tf.Tensor: shape=(3,), dtype=float64, numpy=array([1.45353019, 1.06713909, 0.9259442 ])>,
 tensor([1.4535, 1.0671, 0.9259], dtype=torch.float64))

# Row Summation

In [10]:
sum1 = np.einsum('ij->i', X)
sum2 = tensorflow.einsum('ij->i', X_tf)
sum3 = torch.einsum('ij->i', X_torch)
sum1, sum2, sum3

(array([1.97982444, 1.46678904]),
 <tf.Tensor: shape=(2,), dtype=float64, numpy=array([1.97982444, 1.46678904])>,
 tensor([1.9798, 1.4668], dtype=torch.float64))

# Matrix - Vector Multiplication

In [11]:
V = np.random.rand(1,3)
V_torch = torch.tensor(V)
V_tf = tensorflow.convert_to_tensor(V)

In [12]:
m1 = np.einsum('ij, kj->ik', X, V)
m2 = torch.einsum('ij, kj->ik', X_torch, V_torch)
m3 = tensorflow.einsum('ij, kj->ik', X_tf, V_tf)
m1, m2, m3

(array([[1.15494172],
        [0.81501854]]),
 tensor([[1.1549],
         [0.8150]], dtype=torch.float64),
 <tf.Tensor: shape=(2, 1), dtype=float64, numpy=
 array([[1.15494172],
        [0.81501854]])>)

# Matrix - Matrix Multiplication

In [13]:
m1 = np.einsum('ij, kj->ik', X, X)
m1

array([[1.91278852, 0.5828003 ],
       [0.5828003 , 1.0305194 ]])

In [14]:
m2 = torch.einsum('ij, kj->ik', X_torch, X_torch)
m3 = tensorflow.einsum('ij, kj->ik', X_tf, X_tf)
m1, m2, m3

(array([[1.91278852, 0.5828003 ],
        [0.5828003 , 1.0305194 ]]),
 tensor([[1.9128, 0.5828],
         [0.5828, 1.0305]], dtype=torch.float64),
 <tf.Tensor: shape=(2, 2), dtype=float64, numpy=
 array([[1.91278852, 0.5828003 ],
        [0.5828003 , 1.0305194 ]])>)

In [15]:
m3.numpy()

array([[1.91278852, 0.5828003 ],
       [0.5828003 , 1.0305194 ]])

# Dot product first row with first row of matrix

In [16]:
np.einsum('i,i->', X[0], X[0])

1.9127885216049632

# Dot product with matrix

In [17]:
np.einsum('ij,ij->', X, X)

2.943307917672451

# Hadamard product (elementwise Multiplication)

In [36]:
np.einsum('ij,ij->ij', X, X)

array([[9.99702751e-01, 9.12473796e-01, 6.11975064e-04],
       [2.05824479e-01, 1.25225381e-02, 8.12172379e-01]])

# Outer Product

In [52]:
a = torch.rand((3))
b = torch.rand((5))
torch.einsum('i,j->ij', a, b) == a[:,np.newaxis]*b

tensor([[True, True, True, True, True],
        [True, True, True, True, True],
        [True, True, True, True, True]])

# Batch Matrix Multiplication

In [53]:
a = torch.rand((3, 2, 5))
b = torch.rand((3, 5, 3))
torch.einsum("ijk,ikl->ijl", a, b)

tensor([[[0.9490, 0.8334, 1.3364],
         [0.6576, 0.8837, 1.2689]],

        [[1.4322, 1.6854, 1.3836],
         [2.0124, 2.0319, 1.4551]],

        [[0.8348, 0.6434, 1.1329],
         [0.9645, 0.8896, 0.9203]]])

In [54]:
torch.einsum("ijk,ikl->ijl", a, b)


tensor([[[0.9490, 0.8334, 1.3364],
         [0.6576, 0.8837, 1.2689]],

        [[1.4322, 1.6854, 1.3836],
         [2.0124, 2.0319, 1.4551]],

        [[0.8348, 0.6434, 1.1329],
         [0.9645, 0.8896, 0.9203]]])

# Matrix Diagonal

In [56]:
X = torch.rand((3,3))
torch.einsum("ii->i", X)

tensor([0.6269, 0.5167, 0.8320])

# Matrix Trace

In [57]:
torch.einsum("ii->", X)

tensor(1.9755)