# 1. Repeating letters in diffrent inputs mean those values will be multiplied and those product will be output.

In [1]:
import numpy as np

In [7]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [62]:
A = np.ones((3,5))

B = np.ones((5,3))

In [63]:
A[1]=2

In [64]:
A

array([[1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2.],
       [1., 1., 1., 1., 1.]])

In [65]:
print(np.einsum('ij, ji->ij', A, B))

[[1. 1. 1. 1. 1.]
 [2. 2. 2. 2. 2.]
 [1. 1. 1. 1. 1.]]


In [66]:
np.einsum('ij, jk->ij', A, B)

array([[3., 3., 3., 3., 3.],
       [6., 6., 6., 6., 6.],
       [3., 3., 3., 3., 3.]])

# How does this work?

In [72]:
A = np.ones((3,5))
A[1] = 2
B = np.ones((5,2))

In [73]:
M = np.einsum('ik, kj->ij', A, B)
M

array([[ 5.,  5.],
       [10., 10.],
       [ 5.,  5.]])

In [74]:
M2 = np.empty((3,2))
for i in range(3):
    for j in range(2):
        total = 0
        for k in range(5):
            total += A[i,k]*B[k, j]

        M2[i, j] = total

In [75]:
M2 == M

array([[ True,  True],
       [ True,  True],
       [ True,  True]])

# Omitting a letter means that axis will be summed

# We can return the un-summed axes in any order