# Why Einsum
<img src="img.png" width=800>

<img src="img_1.png" width=800>

<img src="img_2.png" width=800>

<img src="img_3.png" width=800>

In [4]:
import numpy as np
A = [[1,2,3],[4,5,6],[7,8,9]]
B = [[1,2,3],[4,5,6],[7,8,9]]
M = np.einsum('ik,kj->ij', A, B)
M

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [7]:
np.matmul(A, B) == M

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

<img src="img_4.png" width=800>

In [11]:
A = np.random.rand(3,5)
B = np.random.rand(5, 2)
M = np.einsum('ik, kj -> ij', A, B)
M

array([[1.56799041, 1.10154221],
       [1.77564588, 1.17556795],
       [1.68085111, 1.22567633]])

In [10]:
M == np.matmul(A, B)

array([[ True, False],
       [ True,  True],
       [ True,  True]])

In [12]:
np.matmul(A, B)

array([[1.56799041, 1.10154221],
       [1.77564588, 1.17556795],
       [1.68085111, 1.22567633]])

<img src="img_5.png" width=800>


In [15]:
a = np.random.rand(3)
b = np.random.rand(5)
c = np.einsum('i, j -> i', a, b)
c

array([1.37424028, 2.22417887, 1.07271622])

In [16]:
d = np.einsum('i, j -> j', a, b)
d

array([1.09324603, 0.70513099, 0.64731323, 1.01159374, 1.21385138])

# Outer product

In [22]:
e = np.einsum('i,j->ij', a, b)
e

array([[0.32163117, 0.20744837, 0.19043848, 0.2976092 , 0.35711306],
       [0.52055325, 0.3357508 , 0.30822065, 0.48167421, 0.57797995],
       [0.25106161, 0.16193182, 0.14865409, 0.23231033, 0.27875837]])

In [26]:
a[:,np.newaxis]*b == e

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

<img src="img_6.png" width=800>

<img src="img_7.png" width=800>

<img src="img_8.png" width=800>

<img src="img_9.png" width=800>

<img src="img_10.png" width=800>